### ISSUE TITLE
HelloWorld file not saved as .md

### ISSUE THREAD

**Issue by rayschneider** [jaydatawiz/datasciencecoursera#1]
Hi,

I'm reviewing your file for the coursera assessment.  The HelloWorld file you saved needs to be saved as helloworld.md so it shows up as a markdown file.  Please update and let me know so I can give you full credit.

Cheers!

**Comment by jaydatawiz** [comment]
YES I HAVE REVIEWED AND CHANGED THE NAME OF THE FILE YO HELLO WORLD AND THANK YOU FOR TE FEEDBACK
